version: '3'

services:
  cv-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./evaluation_reports:/app/evaluation_reports
      - ./templates:/app/templates
      - ./static:/app/static
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production 